// Mocks generated by Mockito 5.1.0 from annotations
// in flutter_with_getx/test/ui/login/login_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_with_getx/data/model/response/api_response.dart' as _i2;
import 'package:flutter_with_getx/data/repository/auth_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeApiResponse_0 extends _i1.Fake implements _i2.ApiResponse {}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse> auth({String? email, String? password}) =>
      (super.noSuchMethod(
          Invocation.method(#auth, [], {#email: email, #password: password}),
          returnValue:
              Future<_i2.ApiResponse>.value(_FakeApiResponse_0())) as _i4
          .Future<_i2.ApiResponse>);
  @override
  _i4.Future<_i2.ApiResponse> refresh() =>
      (super.noSuchMethod(Invocation.method(#refresh, []),
              returnValue: Future<_i2.ApiResponse>.value(_FakeApiResponse_0()))
          as _i4.Future<_i2.ApiResponse>);
}
