name: ios build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'
        channel: 'any'
        architecture: x64
    - run: dart pub global activate fvm
    - run: fvm install
    - run: fvm flutter pub get
    - run: fvm flutter test
    - run: fvm flutter build ios --release --no-codesign