name: ios build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version
    - run: dart pub global activate fvm
    - run: fvm install
    - run: fvm flutter pub get

    - name: Restore Firebase Settings
      run: echo -n "${{ secrets.LIB_FIREBASE_OPTIONS }}" | base64 -d > lib/firebase_options.dart
    - run: echo -n "${{ secrets.ANDROID_GOOGLE_SERVICES }}" | base64 -d > android/app/google-services.json
    - run: echo -n "${{ secrets.IOS_FIREBASE_APP_ID_FILE }}" | base64 -d > ios/firebase_app_id_file.json

    - run: fvm flutter test
    - run: fvm flutter build ios --release --no-codesign