name: android build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'
        channel: 'any'
    - run: dart pub global activate fvm
    - run: fvm flutter pub get
    - run: fvm flutter test
    - run: fvm flutter build apk
    - run: fvm flutter build appbundle