name: android build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.x'
        channel: 'any'
    - run: dart pub global activate fvm
    - run: fvm install
    - run: fvm flutter pub get

    # Secrets からrelease.jks を生成
    - name: Create release.jks
      run: echo -n ${{ secrets.ANDROID_KEY_JKS }} | base64 -d > "`pwd`/upload-keystore.jks"

    # Secrets から key.properties を生成
    - name: Create key.properties
      run: |
        echo "storeFile=`pwd`/upload-keystore.jks" > android/key.properties
        echo 'storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}' >> android/key.properties
        echo 'keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}' >> android/key.properties
        echo 'keyAlias=upload' >> android/key.properties
        cat android/key.properties

    - run: fvm flutter test
    - run: fvm flutter build apk --flavor production
    - run: fvm flutter build appbundle --flavor production